import streamlit as st

METRICS = [
    {
        "id": "08",
        "title": "DeepEval Foundations",
        "subtitle": "Turn AI quality from a manual opinion into a repeatable automated test.",
        "plain": [
            "Traditional software tests often compare a clear expected value with an actual value. AI responses are different: two answers can use different words and still both be correct. DeepEval gives QA engineers evaluation metrics that score qualities such as relevance, faithfulness, and retrieval quality.",
            "In this course we use DeepEval as an automated QA layer around the same RAG flow you already learned. The RAG application produces a question, retrieved chunks, and an answer. DeepEval then evaluates those outputs and decides whether they meet our quality thresholds.",
        ],
        "why": "Without automated evaluation, a team can manually test a few prompts but may miss regressions after prompt, chunking, retrieval, model, or document changes. DeepEval lets us run the same quality checks repeatedly and later place them in CI/CD.",
        "visual": [("❓", "Input", "Question sent to the RAG app"), ("🔎", "Retrieval context", "Chunks returned by the retriever"), ("💬", "Actual output", "Answer generated by the app"), ("🎯", "Expected output", "Known ideal answer when needed"), ("📊", "Metric", "Score + reason + PASS/FAIL")],
        "example": "A test asks how long a reset link lasts. The agent retrieves the correct 30-minute policy and answers '30 minutes'. DeepEval can independently check whether the answer is relevant, faithful to the evidence, and whether retrieval quality was good.",
        "code": '''from deepeval.metrics import AnswerRelevancyMetric\nfrom deepeval.test_case import LLMTestCase\n\ntest_case = LLMTestCase(\n    input="How long is the reset link valid?",\n    actual_output="The reset link is valid for 30 minutes.",\n)\n\nmetric = AnswerRelevancyMetric(threshold=0.7)\nmetric.measure(test_case)\n\nprint(metric.score)\nprint(metric.reason)''',
        "questions": [
            ("Why do we need AI evaluation metrics?", "Because exact-string assertions are too brittle for natural-language answers. Metrics evaluate a quality dimension instead of requiring identical wording."),
            ("What does a threshold do?", "It defines the minimum acceptable metric score. Below the threshold, the automated quality check fails."),
            ("Why is the reason useful?", "The score tells us how much the test passed or failed; the reason helps a tester understand and debug why."),
        ],
        "exercise": "List the four pieces of data an AI QA engineer may capture from a RAG run: question, generated answer, retrieved chunks, and known ideal answer. Map them to DeepEval field names.",
        "answer": "input = question; actual_output = generated answer; retrieval_context = retrieved chunks; expected_output = known ideal/reference answer.",
    },
    {
        "id": "09",
        "title": "Answer Relevancy",
        "subtitle": "Did the chatbot actually answer what the user asked?",
        "plain": [
            "Answer Relevancy evaluates the generated response against the user's input. It is useful when the chatbot says something that may be true but does not actually answer the question.",
            "This is a generator metric. It does not require an expected answer and it does not prove factual correctness. A response can be relevant to the question but still contain an unsupported fact, which is why we also need Faithfulness.",
        ],
        "why": "Use it to catch off-topic answers, rambling responses, answers that focus on the wrong part of a question, or cases where the model repeats context without answering the user's intent.",
        "visual": [("❓", "Question", "How long is my reset link valid?"), ("💬", "Agent answer", "Support is open 9 AM–5 PM."), ("⚖️", "Compare intent", "Does this answer the question?"), ("❌", "Low relevancy", "Related system, wrong intent")],
        "example": "Question: 'Can I return an opened item?' Answer: 'Returns are available within 30 days.' The answer is related to returns but does not address the important opened/unopened condition, so relevancy may be reduced.",
        "code": '''from deepeval.metrics import AnswerRelevancyMetric\nfrom deepeval.test_case import LLMTestCase\n\ncase = LLMTestCase(\n    input="How long is the reset link valid?",\n    actual_output="The reset link is valid for 30 minutes.",\n)\n\nmetric = AnswerRelevancyMetric(threshold=0.7)\nmetric.measure(case)\nprint("Score:", metric.score)\nprint("Reason:", metric.reason)''',
        "questions": [
            ("What fields are required?", "input and actual_output."),
            ("Does a high Answer Relevancy score prove the answer is factually supported?", "No. It measures whether the response addresses the input. Faithfulness checks support against retrieved evidence."),
            ("When would this fail?", "When the answer is off-topic, avoids the question, focuses on a different intent, or contains mostly irrelevant statements."),
        ],
        "exercise": "Question: 'What is the remote-work probation rule?' Agent answer: 'Employees receive 15 vacation days.' Which metric should clearly flag this first?",
        "answer": "Answer Relevancy, because the response does not address the user's remote-work question.",
    },
    {
        "id": "10",
        "title": "Faithfulness",
        "subtitle": "Did the answer stay faithful to the retrieved evidence?",
        "plain": [
            "Faithfulness compares claims in the actual answer with the retrieval context. If the model changes a number, invents a condition, or contradicts the chunks that were supplied, the faithfulness score should fall.",
            "This is one of the most important generator metrics for RAG testing because it helps distinguish a generation problem from a retrieval problem. If retrieval returned the correct evidence but Faithfulness fails, the generator likely introduced the defect.",
        ],
        "why": "Use Faithfulness for hallucination-like behavior inside RAG: invented numbers, unsupported dates, changed policy rules, contradictory claims, or extra facts that were not present in the retrieved evidence.",
        "visual": [("🔎", "Evidence", "Reset links expire after 30 minutes"), ("💬", "Answer", "Reset links expire after 60 minutes"), ("⚖️", "Compare claims", "60 contradicts 30"), ("❌", "Faithfulness FAIL", "Generator changed the fact")],
        "example": "Retrieved context says '$500 annual allowance'. The answer says '$500 annual allowance that expires September 30'. The amount is supported, but the deadline is invented, so the answer is not fully faithful.",
        "code": '''from deepeval.metrics import FaithfulnessMetric\nfrom deepeval.test_case import LLMTestCase\n\ncase = LLMTestCase(\n    input="How long is the reset link valid?",\n    actual_output="The reset link is valid for 30 minutes.",\n    retrieval_context=[\n        "Password reset links expire after 30 minutes."\n    ],\n)\n\nmetric = FaithfulnessMetric(threshold=0.8)\nmetric.measure(case)\nprint("Score:", metric.score)\nprint("Reason:", metric.reason)''',
        "questions": [
            ("What fields are required?", "input, actual_output, and retrieval_context."),
            ("If retrieval is wrong but the answer faithfully repeats it, can Faithfulness still pass?", "Yes. Faithfulness evaluates the answer against the supplied retrieval context. That is why retriever metrics must also be tested."),
            ("What failure does this help isolate?", "A generator/grounding failure when good evidence was supplied but the model contradicted or exceeded it."),
        ],
        "exercise": "Evidence says employees receive 15 vacation days. The answer says employees receive 20 days. Which stage appears broken if the evidence panel is correct?",
        "answer": "Generation/grounding. Faithfulness should fail because the answer contradicts the retrieved evidence.",
    },
    {
        "id": "11",
        "title": "Contextual Relevancy",
        "subtitle": "Did the retriever return context that is actually useful for this question?",
        "plain": [
            "Contextual Relevancy evaluates the retrieval context against the user's input. It asks whether the retrieved statements are useful for answering that specific question.",
            "This is a retriever metric. It is especially useful for noisy retrieval where one correct chunk is mixed with several unrelated chunks. Even if the final answer happens to be correct, noisy context can increase cost and create future hallucination risk.",
        ],
        "why": "Use it to detect unrelated chunks, excessive retrieval noise, poor semantic matching, and cases where the retriever selects information from a similar but different topic.",
        "visual": [("❓", "Question", "How long is the reset link valid?"), ("🔎", "Chunk A", "Reset link: 30 minutes"), ("📦", "Chunk B", "Office opens at 9 AM"), ("⚖️", "Judge context", "A relevant, B irrelevant"), ("📊", "Relevancy", "Lower when context is noisy")],
        "example": "For a password-reset question, returning reset-link policy is relevant. Returning office hours and profile-photo instructions is irrelevant retrieval noise.",
        "code": '''from deepeval.metrics import ContextualRelevancyMetric\nfrom deepeval.test_case import LLMTestCase\n\ncase = LLMTestCase(\n    input="How long is the reset link valid?",\n    actual_output="It is valid for 30 minutes.",\n    retrieval_context=[\n        "Password reset links expire after 30 minutes.",\n        "Support is open from 9 AM to 5 PM.",\n    ],\n)\n\nmetric = ContextualRelevancyMetric(threshold=0.7)\nmetric.measure(case)\nprint(metric.score, metric.reason)''',
        "questions": [
            ("What fields are required?", "input, actual_output, and retrieval_context."),
            ("What does this metric evaluate: generator or retriever?", "Retriever."),
            ("Why care about irrelevant chunks if the answer is still correct?", "Noise wastes context, can increase cost, and can make future answers less reliable."),
        ],
        "exercise": "A question asks about refunds, but three of the four returned chunks discuss shipping. What retrieval problem is visible?",
        "answer": "Low contextual relevancy: most retrieved information is not useful for the question.",
    },
    {
        "id": "12",
        "title": "Contextual Precision",
        "subtitle": "Are the best answer-bearing chunks ranked ahead of irrelevant chunks?",
        "plain": [
            "Contextual Precision focuses on ranking. It checks whether relevant chunks appear higher in retrieval_context than irrelevant chunks. This matters when the system retrieves several candidates and their order determines what the LLM pays most attention to.",
            "Contextual Precision is reference-based, so we provide expected_output. The metric uses the expected answer to help judge which retrieved nodes are relevant and then evaluates whether the ranking order is good.",
        ],
        "why": "Use it when you are tuning similarity search, reranking, Top-K behavior, hybrid search, or any system where the same chunks may be returned but in a poor order.",
        "visual": [("🥇", "Rank 1", "Office hours — irrelevant"), ("🥈", "Rank 2", "Reset link 30 minutes — relevant"), ("🥉", "Rank 3", "Profile settings — irrelevant"), ("⚠️", "Precision issue", "Best evidence should rank first")],
        "example": "If the correct refund-policy chunk is returned at rank 4 while three unrelated shipping chunks rank above it, retrieval may have acceptable recall but poor contextual precision.",
        "code": '''from deepeval.metrics import ContextualPrecisionMetric\nfrom deepeval.test_case import LLMTestCase\n\ncase = LLMTestCase(\n    input="How long is the reset link valid?",\n    actual_output="It is valid for 30 minutes.",\n    expected_output="The reset link expires after 30 minutes.",\n    retrieval_context=[\n        "Password reset links expire after 30 minutes.",\n        "Support is open from 9 AM to 5 PM.",\n    ],\n)\n\nmetric = ContextualPrecisionMetric(threshold=0.7)\nmetric.measure(case)\nprint(metric.score, metric.reason)''',
        "questions": [
            ("What extra field does this metric need?", "expected_output, in addition to input, actual_output, and retrieval_context."),
            ("What does a precision failure mean?", "Relevant evidence is ranked too low compared with irrelevant evidence."),
            ("How is this different from Contextual Relevancy?", "Relevancy asks whether retrieved content is useful overall; Precision focuses on whether the useful nodes are ranked ahead of irrelevant ones."),
        ],
        "exercise": "The correct chunk is in Top-K, but always appears last after several irrelevant chunks. Which metric is designed to catch ranking quality?",
        "answer": "Contextual Precision.",
    },
    {
        "id": "13",
        "title": "Contextual Recall",
        "subtitle": "Did retrieval capture all information needed for the ideal answer?",
        "plain": [
            "Contextual Recall evaluates whether the retrieval context contains the information required to support the expected output. It is about completeness rather than ranking.",
            "This metric is important for questions whose correct answer requires multiple facts, conditions, or exceptions. Retrieval can return one relevant chunk and still fail because another necessary piece of evidence is missing.",
        ],
        "why": "Use it for multi-fact answers, policies with exceptions, multi-section documents, rule + condition questions, and situations where the correct answer exists in the source but some necessary evidence never reaches the LLM.",
        "visual": [("🎯", "Expected answer", "30 days AND unopened"), ("🔎", "Retrieved", "30 days only"), ("🧩", "Missing fact", "Unopened condition"), ("❌", "Recall gap", "Context is incomplete")],
        "example": "Expected answer: 'Returns are allowed within 30 days only if unopened.' Retrieval returns only 'Returns are allowed within 30 days.' The retrieved context is relevant, but recall is incomplete because the condition is missing.",
        "code": '''from deepeval.metrics import ContextualRecallMetric\nfrom deepeval.test_case import LLMTestCase\n\ncase = LLMTestCase(\n    input="What is the return policy?",\n    actual_output="Returns are allowed within 30 days if unopened.",\n    expected_output="Returns are allowed within 30 days if unopened.",\n    retrieval_context=[\n        "Returns are allowed within 30 days if unopened."\n    ],\n)\n\nmetric = ContextualRecallMetric(threshold=0.7)\nmetric.measure(case)\nprint(metric.score, metric.reason)''',
        "questions": [
            ("What does Contextual Recall need?", "input, actual_output, expected_output, and retrieval_context."),
            ("What does low recall mean?", "The retrieved context is missing information needed for the ideal/expected answer."),
            ("Can relevancy be high while recall is low?", "Yes. A retrieved chunk can be relevant but incomplete."),
        ],
        "exercise": "Retrieval returns the vacation entitlement but misses the manager-approval exception needed for the full expected answer. Which metric should detect completeness loss?",
        "answer": "Contextual Recall.",
    },
    {
        "id": "14",
        "title": "Automate the DocPilotAI RAG Pipeline",
        "subtitle": "Capture real answers and retrieval chunks from the same type of PDF pipeline used by the app.",
        "plain": [
            "A useful AI evaluation test should call the system under test, not only score hard-coded sample strings. We therefore separate the RAG pipeline into reusable Python functions that can load a PDF or text source, chunk it, retrieve Top-K evidence, call the LLM, and return both answer and retrieval_context.",
            "The Streamlit UI is only one client of that logic. Pytest can call the same evaluation-friendly pipeline without clicking buttons. This is how an interactive PDF agent becomes automatable.",
        ],
        "why": "This is the bridge from manual AI QA to automation. The test captures real runtime output, then DeepEval scores it.",
        "visual": [("📄", "PDF/text fixture", "Known training knowledge"), ("⚙️", "RAG pipeline", "Chunk + retrieve + generate"), ("🧪", "Pytest", "Calls pipeline with golden question"), ("📊", "DeepEval", "Scores answer and retrieval"), ("🚦", "Assertion", "Quality threshold passes/fails")],
        "example": "A golden test supplies the question 'How long is the reset link valid?' and expected answer '30 minutes'. The automated pipeline retrieves chunks and generates the answer at runtime. DeepEval then evaluates the runtime result.",
        "code": '''from rag_eval import RAGPipeline\n\npipeline = RAGPipeline.from_text(\n    "Password reset links expire after 30 minutes."\n)\n\nresult = pipeline.ask(\n    "How long is the reset link valid?"\n)\n\nprint(result.answer)\nprint(result.retrieval_context)''',
        "questions": [
            ("Why not automate Streamlit button clicks for every evaluation?", "The core RAG logic is faster and more reliable to test directly. UI automation can be added separately for UI behavior."),
            ("What runtime data must the pipeline return?", "At minimum the actual answer and the retrieved context, plus the original input."),
            ("Can the helper also load a real PDF?", "Yes. The course helper includes from_pdf(path), which uses pypdf extraction before the same chunk/retrieval flow."),
        ],
        "exercise": "Explain why exposing retrieval_context is essential for RAG evaluation.",
        "answer": "Without retrieval_context, QA cannot directly evaluate grounding, retrieval relevance, ranking, or retrieval completeness, and root-cause analysis becomes much weaker.",
    },
    {
        "id": "15",
        "title": "Pytest + Golden Data",
        "subtitle": "Run multiple AI test cases repeatedly instead of testing one prompt at a time.",
        "plain": [
            "A golden dataset is a controlled collection of representative questions and expected answers. Pytest parameterization lets us run the same RAG pipeline and DeepEval metrics for every golden case.",
            "Good golden data should include normal questions, policy conditions, paraphrases, and important business rules. Keep the dataset small and high-quality first; expand it as real defects and user scenarios are discovered.",
        ],
        "why": "This turns one-off metric demos into a regression suite. When the pipeline changes, the same cases run again and show whether AI quality improved or regressed.",
        "visual": [("📚", "Golden JSON", "Question + expected answer"), ("🔁", "pytest parametrize", "Run every case"), ("⚙️", "RAG call", "Runtime answer + chunks"), ("📊", "5 metrics", "Generator + retriever checks"), ("✅", "Regression suite", "Repeatable quality evidence")],
        "example": "Three golden cases cover reset-link duration, return policy, and vacation rules. The same test function executes all three and applies selected DeepEval metrics.",
        "code": '''import pytest\nfrom deepeval import assert_test\nfrom deepeval.metrics import AnswerRelevancyMetric, FaithfulnessMetric\nfrom deepeval.test_case import LLMTestCase\n\n@pytest.mark.parametrize("golden", GOLDENS)\ndef test_rag_quality(golden, rag_pipeline):\n    result = rag_pipeline.ask(golden["input"])\n    case = LLMTestCase(\n        input=golden["input"],\n        actual_output=result.answer,\n        expected_output=golden["expected_output"],\n        retrieval_context=result.retrieval_context,\n    )\n    assert_test(case, [\n        AnswerRelevancyMetric(threshold=0.7),\n        FaithfulnessMetric(threshold=0.8),\n    ])''',
        "questions": [
            ("What belongs in golden data?", "Stable, important questions with known expected answers or behavior."),
            ("Why parameterize tests?", "One test function can run many golden cases consistently."),
            ("Should every possible user prompt be in the golden dataset?", "No. Start with high-value representative cases and expand based on risk, incidents, and defects."),
        ],
        "exercise": "Create one new golden case for a rule with an exception. Include input and expected_output.",
        "answer": "Example: input='Can a new employee work remotely immediately?'; expected_output='No. New employees must complete their first 90 days in the office before the normal remote-work rule applies.'",
    },
    {
        "id": "16",
        "title": "CI/CD Quality Gate with GitHub Actions",
        "subtitle": "Run DeepEval automatically on every important code change.",
        "plain": [
            "Once AI evaluation tests run locally, CI/CD makes them part of the engineering workflow. GitHub Actions installs the project, receives the evaluation API key securely from repository secrets, runs pytest/DeepEval, and marks the job green or red.",
            "The goal is not to block every change because an LLM score moved slightly. Start with meaningful thresholds and a focused golden suite. A red pipeline should tell the team which quality dimension regressed so they can investigate retrieval, generation, prompts, chunking, or test data.",
        ],
        "why": "CI turns AI evaluation into a quality gate. Prompt, model, chunking, and retrieval changes are tested before they quietly reach users.",
        "visual": [("💻", "Developer change", "Prompt/retrieval/model code"), ("⬆️", "Push / PR", "GitHub receives change"), ("⚙️", "Actions", "Install dependencies"), ("🧪", "DeepEval suite", "Run golden cases + metrics"), ("🚦", "Quality gate", "Green = pass, red = investigate")],
        "example": "A developer changes chunk size. Contextual Recall drops below threshold for a policy-with-exception case. GitHub Actions fails before merge, pointing QA and engineering toward a retrieval completeness regression.",
        "code": '''name: RAG DeepEval Quality Gate\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  evaluate-rag:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt\n      - name: Run RAG evaluation tests\n        env:\n          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}\n          OPENAI_MODEL: gpt-4.1-mini\n        run: pytest tests/test_deepeval_rag.py -v''',
        "questions": [
            ("Where should OPENAI_API_KEY be stored?", "In GitHub repository/environment secrets, never committed in source code."),
            ("What makes the CI job fail?", "A pytest/DeepEval assertion whose metric score is below its configured threshold, or another test/runtime error."),
            ("How should QA investigate a red pipeline?", "Open the failing case, identify which metric failed, read its reason, inspect runtime retrieval context and answer, then decide whether the issue is retriever, generator, data, or threshold design."),
        ],
        "exercise": "A PR causes Contextual Relevancy to fail while Faithfulness still passes. Where should the team investigate first?",
        "answer": "The retriever/search behavior first. The generator may be faithfully using the context it received, but the context itself is not sufficiently relevant to the question.",
    },
]

st.markdown("""
<style>
.deep-hero{background:linear-gradient(135deg,#101827,#312e81,#075985);padding:26px 29px;border-radius:24px;color:#fff;margin:8px 0 18px;box-shadow:0 16px 42px rgba(15,23,42,.16)}
.deep-hero h1{font-size:31px;margin:0}.deep-hero p{color:#dbeafe;font-size:15px;line-height:1.6;max-width:900px;margin:8px 0 0}
.deep-path{display:grid;grid-template-columns:repeat(9,minmax(90px,1fr));gap:6px;margin:12px 0 20px}.deep-path div{background:white;border:1px solid #dbe4f0;border-radius:12px;padding:10px 7px;font-size:11px;text-align:center;font-weight:750}.deep-path b{display:block;color:#4f46e5;margin-bottom:3px}
.deep-card{background:white;border:1px solid #e2e8f0;border-radius:18px;padding:19px 20px;margin:12px 0;box-shadow:0 5px 18px rgba(15,23,42,.04)}.deep-copy{font-size:15.5px;line-height:1.72;color:#334155}.why{background:#eff6ff;border-left:4px solid #3b82f6;border-radius:14px;padding:15px 17px;color:#1e3a8a;line-height:1.6}
.metric-flow{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:10px;margin:13px 0 20px}.metric-node{background:linear-gradient(145deg,#0f172a,#1e293b);color:white;border-radius:17px;padding:16px;text-align:center;min-height:120px}.metric-node .i{font-size:26px}.metric-node b{display:block;margin:7px 0 4px}.metric-node span{font-size:12px;color:#cbd5e1;line-height:1.4}
.code-label{font-size:12px;font-weight:850;color:#4f46e5;text-transform:uppercase;letter-spacing:.07em}.field-table{background:#f8fafc;border:1px solid #e2e8f0;border-radius:14px;padding:13px 15px;margin:10px 0}
@media(max-width:900px){.deep-path{grid-template-columns:repeat(3,1fr)}}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="deep-hero">
<h1>🧪 DeepEval Automation for RAG QA</h1>
<p>Phase 2 takes the RAG concepts you learned and turns them into automated AI quality tests. You will learn what each metric measures, which test-case fields it needs, how to interpret failures, how to call a reusable PDF/RAG pipeline, and how to run the suite in CI/CD.</p>
</div>
""", unsafe_allow_html=True)

st.markdown("### Automation journey")
st.markdown('<div class="deep-path">' + ''.join(f'<div><b>{m["id"]}</b>{m["title"]}</div>' for m in METRICS) + '</div>', unsafe_allow_html=True)

labels = [f"{m['id']} — {m['title']}" for m in METRICS]
selected = st.selectbox("Choose DeepEval module", labels, key="deepeval_module")
module = METRICS[labels.index(selected)]

st.markdown(f"<div class='deep-card'><div style='font-size:12px;font-weight:900;color:#4f46e5'>MODULE {module['id']}</div><div style='font-size:25px;font-weight:900;margin-top:3px'>{module['title']}</div><div style='color:#64748b;margin-top:5px'>{module['subtitle']}</div></div>", unsafe_allow_html=True)

learn, code, qa, exercise = st.tabs(["📘 Learn", "💻 Code Example", "❓ Questions & Answers", "🧪 Exercise"])

with learn:
    st.markdown("## Understand the metric / skill")
    st.markdown('<div class="deep-copy">' + ''.join(f'<p>{p}</p>' for p in module['plain']) + '</div>', unsafe_allow_html=True)
    st.markdown("### Why QA uses it")
    st.markdown(f'<div class="why">{module["why"]}</div>', unsafe_allow_html=True)
    st.markdown("### Visual flow")
    flow = '<div class="metric-flow">'
    for icon, title, copy in module['visual']:
        flow += f'<div class="metric-node"><div class="i">{icon}</div><b>{title}</b><span>{copy}</span></div>'
    flow += '</div>'
    st.markdown(flow, unsafe_allow_html=True)
    st.markdown("### Worked example")
    st.info(module['example'])

with code:
    st.markdown("## Read the automation code")
    st.write("The goal is to understand what each field represents before copying the code into a test suite.")
    st.code(module['code'], language="python" if module['id'] != '16' else "yaml")
    if module['id'] in {"09", "10", "11", "12", "13"}:
        requirements = {
            "09": "input + actual_output",
            "10": "input + actual_output + retrieval_context",
            "11": "input + actual_output + retrieval_context",
            "12": "input + actual_output + expected_output + retrieval_context",
            "13": "input + actual_output + expected_output + retrieval_context",
        }
        st.markdown(f'<div class="field-table"><b>Required LLMTestCase fields:</b> {requirements[module["id"]]}</div>', unsafe_allow_html=True)
    st.caption("The repository includes runnable examples in rag_eval.py and tests/test_deepeval_rag.py.")

with qa:
    st.markdown("## Check your understanding")
    for i, (q, a) in enumerate(module['questions'], 1):
        with st.expander(f"Q{i}. {q}"):
            st.success(a)

with exercise:
    st.markdown("## Small student exercise")
    st.info(module['exercise'])
    st.text_area("Your reasoning", key=f"deepeval_answer_{module['id']}", placeholder="Write what should happen, which metric/test layer is involved, and why...", height=120)
    if st.button("Show suggested answer", key=f"deepeval_show_{module['id']}"):
        st.success(module['answer'])

st.divider()
st.markdown("### Files students will use in the repository")
st.code("""rag_eval.py                         # reusable RAG pipeline for automation\ntests/data/training_policy.txt         # controlled source knowledge\ntests/data/golden_cases.json           # golden questions and expected answers\ntests/test_deepeval_rag.py             # pytest + DeepEval regression suite\n.github/workflows/rag-deepeval.yml      # CI/CD quality gate""", language="text")
st.caption("CI requires an OPENAI_API_KEY GitHub Actions secret. Keep secrets out of source control.")