import ast
import io
import json
import os
import zipfile
from pathlib import Path

import streamlit as st


PROJECT_FILES = [
    "requirements.txt",
    "rag_pipeline.py",
    "tests/data/golden_cases.json",
    "tests/test_deepeval.py",
    ".github/workflows/deepeval.yml",
]

STARTERS = {
    "requirements.txt": "# Add the packages needed for the RAG evaluation project\n",
    "rag_pipeline.py": "# Build your reusable RAG pipeline here.\n# Goal: load text, chunk, retrieve Top-K context, call the LLM, and return answer + retrieval_context.\n",
    "tests/data/golden_cases.json": "[\n  \n]\n",
    "tests/test_deepeval.py": "# Write your pytest + DeepEval regression tests here.\n",
    ".github/workflows/deepeval.yml": "# Build the GitHub Actions quality gate here.\n",
}

SOLUTIONS = {
    "requirements.txt": """openai>=1,<3
pypdf>=5,<7
scikit-learn>=1.5,<2
pytest>=8,<9
deepeval>=3,<4
""",
    "rag_pipeline.py": '''import os
from dataclasses import dataclass

from openai import OpenAI
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


@dataclass
class RAGResult:
    # Keep the original user question for traceability.
    input: str
    # Store the answer generated by the LLM.
    answer: str
    # Store the exact chunks returned by retrieval for DeepEval metrics.
    retrieval_context: list[str]


class RAGPipeline:
    def __init__(self, chunks, top_k=4, model="gpt-4.1-mini"):
        # Save the searchable chunks used by the retriever.
        self.chunks = chunks
        # Save how many chunks should be returned for each question.
        self.top_k = top_k
        # Save the model used to generate the final answer.
        self.model = model
        # Create a lightweight TF-IDF vectorizer for the classroom RAG pipeline.
        self.vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2))
        # Convert every document chunk into a searchable numeric representation.
        self.matrix = self.vectorizer.fit_transform(chunks)

    @staticmethod
    def chunk_text(text, size=1200, overlap=200):
        # Hold all document chunks that we create.
        chunks = []
        # Start reading from the beginning of the document.
        start = 0
        # Continue until the complete document has been chunked.
        while start < len(text):
            # Calculate the end position without going beyond the document.
            end = min(start + size, len(text))
            # Extract and clean one chunk.
            piece = text[start:end].strip()
            # Keep only non-empty chunks.
            if piece:
                chunks.append(piece)
            # Stop after processing the final chunk.
            if end >= len(text):
                break
            # Move forward while keeping overlap with the previous chunk.
            start = end - overlap
        # Return all chunks to the caller.
        return chunks

    @classmethod
    def from_text(cls, text, top_k=4):
        # Split source text into chunks first.
        chunks = cls.chunk_text(text)
        # Build and return an indexed RAG pipeline.
        return cls(chunks, top_k=top_k)

    def retrieve(self, question):
        # Convert the user question into the same TF-IDF space as the chunks.
        query = self.vectorizer.transform([question])
        # Compare the question with every stored chunk.
        scores = cosine_similarity(query, self.matrix).flatten()
        # Sort the chunks from highest similarity to lowest and keep Top-K.
        order = scores.argsort()[::-1][: self.top_k]
        # Return the selected source text in ranked order.
        return [self.chunks[i] for i in order]

    def ask(self, question):
        # Retrieve evidence before asking the language model.
        context = self.retrieve(question)
        # Create the OpenAI client from the environment secret.
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        # Join the retrieved chunks into one prompt context block.
        joined = "\n\n---\n\n".join(context)
        # Tell the LLM to remain grounded in the retrieved document context.
        prompt = f"""Answer only from the supplied context.
If the answer is missing, say: I don't know based on the uploaded document.

CONTEXT:
{joined}

QUESTION:
{question}"""
        # Send the grounded prompt to the model.
        response = client.responses.create(model=self.model, input=prompt)
        # Return both generation output and retrieval evidence for evaluation.
        return RAGResult(question, response.output_text.strip(), context)
''',
    "tests/data/golden_cases.json": '''[
  {
    "id": "reset-link",
    "input": "How long is a password reset link valid?",
    "expected_output": "Password reset links expire after 30 minutes."
  },
  {
    "id": "returns",
    "input": "Can I return an opened product after 20 days?",
    "expected_output": "No. Returns within 30 days require the item to be unopened."
  },
  {
    "id": "remote-work",
    "input": "Can a new employee work remotely immediately?",
    "expected_output": "No. New employees must complete their first 90 days in the office."
  }
]
''',
    "tests/test_deepeval.py": '''import json
from pathlib import Path

import pytest
from deepeval import assert_test
from deepeval.metrics import (
    AnswerRelevancyMetric,
    FaithfulnessMetric,
    ContextualRelevancyMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
)
from deepeval.test_case import LLMTestCase

from rag_pipeline import RAGPipeline


ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="session")
def pipeline():
    # Load controlled source knowledge used by the automated test suite.
    text = (ROOT / "tests" / "data" / "training_policy.txt").read_text()
    # Build the same RAG stages the application uses.
    return RAGPipeline.from_text(text)


def load_goldens():
    # Read reusable questions and expected answers from JSON test data.
    path = ROOT / "tests" / "data" / "golden_cases.json"
    # Convert JSON into Python dictionaries for pytest parametrization.
    return json.loads(path.read_text())


@pytest.mark.parametrize("golden", load_goldens(), ids=lambda g: g["id"])
def test_rag_quality(golden, pipeline):
    # Call the real RAG pipeline instead of hard-coding an actual answer.
    result = pipeline.ask(golden["input"])
    # Package runtime values using DeepEval's standard test-case structure.
    case = LLMTestCase(
        input=golden["input"],
        actual_output=result.answer,
        expected_output=golden["expected_output"],
        retrieval_context=result.retrieval_context,
    )
    # Run generator and retriever checks together as one regression gate.
    metrics = [
        AnswerRelevancyMetric(threshold=0.70),
        FaithfulnessMetric(threshold=0.80),
        ContextualRelevancyMetric(threshold=0.60),
        ContextualPrecisionMetric(threshold=0.60),
        ContextualRecallMetric(threshold=0.60),
    ]
    # Fail pytest when one or more quality thresholds are not met.
    assert_test(case, metrics)
''',
    ".github/workflows/deepeval.yml": '''name: DeepEval RAG Quality Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-rag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DeepEval regression tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest tests/test_deepeval.py -v
''',
}

STEPS = [
    {
        "title": "1 · Create the project dependencies",
        "file": "requirements.txt",
        "goal": "Start from an empty project and decide which packages are required for RAG automation, pytest, and DeepEval.",
        "check": ["deepeval", "pytest", "openai", "scikit-learn"],
        "hint1": "You need one package for LLM calls, one for testing, one for DeepEval metrics, and one for TF-IDF retrieval.",
        "hint2": "Look for these package names: openai, pytest, deepeval, scikit-learn.",
    },
    {
        "title": "2 · Build the reusable RAG pipeline",
        "file": "rag_pipeline.py",
        "goal": "Write the code that chunks source text, retrieves Top-K evidence, calls the LLM, and exposes retrieval_context for DeepEval.",
        "check": ["class RAGPipeline", "def retrieve", "def ask", "TfidfVectorizer", "cosine_similarity", "retrieval_context"],
        "hint1": "The automated test needs more than the answer. It also needs the exact chunks that retrieval returned.",
        "hint2": "Create RAGPipeline with retrieve(question) and ask(question). Return answer plus retrieval_context.",
    },
    {
        "title": "3 · Create the golden dataset",
        "file": "tests/data/golden_cases.json",
        "goal": "Create reusable QA test data containing a stable ID, user question, and expected answer.",
        "check": ["input", "expected_output", "id"],
        "hint1": "Each test needs a name, the prompt sent to the RAG app, and a known correct response.",
        "hint2": "Use JSON objects containing id, input, and expected_output.",
    },
    {
        "title": "4 · Write the DeepEval pytest suite",
        "file": "tests/test_deepeval.py",
        "goal": "Call the RAG pipeline, create an LLMTestCase, add all five metrics, and fail the automated test when thresholds are missed.",
        "check": ["LLMTestCase", "AnswerRelevancyMetric", "FaithfulnessMetric", "ContextualRelevancyMetric", "ContextualPrecisionMetric", "ContextualRecallMetric", "assert_test"],
        "hint1": "The test case needs input, actual_output, expected_output, and retrieval_context.",
        "hint2": "Import all five metrics and pass the LLMTestCase plus metric list into assert_test().",
    },
    {
        "title": "5 · Build the GitHub Actions quality gate",
        "file": ".github/workflows/deepeval.yml",
        "goal": "Run the same tests automatically after a push or pull request.",
        "check": ["actions/checkout", "actions/setup-python", "OPENAI_API_KEY", "pytest", "tests/test_deepeval.py"],
        "hint1": "CI needs checkout, Python, dependency installation, the OpenAI secret, and pytest.",
        "hint2": "Use secrets.OPENAI_API_KEY and run pytest tests/test_deepeval.py -v.",
    },
]


def _init_state():
    st.session_state.setdefault("lab_files", {})
    st.session_state.setdefault("lab_step", 0)
    st.session_state.setdefault("lab_messages", {})


def _validate_python(source):
    try:
        ast.parse(source)
        return True, "Python syntax is valid."
    except SyntaxError as exc:
        return False, f"Python syntax error on line {exc.lineno}: {exc.msg}"


def _validate_file(filename, source, required):
    if filename.endswith(".py"):
        ok, message = _validate_python(source)
        if not ok:
            return False, message
    if filename.endswith(".json"):
        try:
            data = json.loads(source)
            if not isinstance(data, list) or not data:
                return False, "Golden JSON must contain at least one test case."
        except Exception as exc:
            return False, f"JSON is not valid: {exc}"
    missing = [token for token in required if token not in source]
    if missing:
        return False, "Still missing: " + ", ".join(missing)
    return True, "Step complete — the important building blocks are present."


def _project_zip(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(path, content)
        archive.writestr(
            "tests/data/training_policy.txt",
            "Password reset links expire after 30 minutes.\n\n"
            "Items may be returned within 30 days only if unopened.\n\n"
            "New employees must complete their first 90 days in the office before remote work begins.\n",
        )
    return buffer.getvalue()


def render_deepeval_project_lab():
    _init_state()

    st.markdown("## 🧑‍💻 Build It Yourself — DeepEval Project Lab")
    st.write(
        "Instead of copying a finished repository, build the automation project one file at a time. "
        "The left side acts like a small file explorer and the editor acts like your VS Code workspace."
    )

    progress = sum(1 for i in range(len(STEPS)) if st.session_state.lab_messages.get(i) == "passed")
    st.progress(progress / len(STEPS), text=f"Project progress: {progress}/{len(STEPS)} files validated")

    left, right = st.columns([0.28, 0.72], gap="large")

    with left:
        st.markdown("### Explorer")
        for i, step in enumerate(STEPS):
            status = "✅" if st.session_state.lab_messages.get(i) == "passed" else "○"
            if st.button(f"{status} {step['file']}", key=f"lab_nav_{i}", use_container_width=True):
                st.session_state.lab_step = i
                st.rerun()

        st.markdown("---")
        st.caption("Your virtual project")
        for file in PROJECT_FILES:
            icon = "📄" if file in st.session_state.lab_files else "▫️"
            st.write(f"{icon} `{file}`")
        st.write("📄 `tests/data/training_policy.txt` *(provided fixture)*")

    step_index = st.session_state.lab_step
    step = STEPS[step_index]
    filename = step["file"]

    with right:
        st.markdown(f"### {step['title']}")
        st.info(step["goal"])

        if filename not in st.session_state.lab_files:
            st.write(f"The file `{filename}` does not exist yet.")
            if st.button(f"＋ Create {filename}", type="primary", key=f"create_{step_index}"):
                st.session_state.lab_files[filename] = STARTERS[filename]
                st.rerun()
        else:
            source = st.text_area(
                filename,
                value=st.session_state.lab_files[filename],
                height=420,
                key=f"editor_{step_index}",
                label_visibility="collapsed",
            )
            st.session_state.lab_files[filename] = source

            c1, c2, c3 = st.columns(3)
            with c1:
                if st.button("▶ Validate file", type="primary", key=f"validate_{step_index}", use_container_width=True):
                    ok, message = _validate_file(filename, source, step["check"])
                    if ok:
                        st.session_state.lab_messages[step_index] = "passed"
                        st.success(message)
                    else:
                        st.error(message)
            with c2:
                with st.popover("💡 Hints", use_container_width=True):
                    st.markdown("**Hint 1**")
                    st.write(step["hint1"])
                    st.markdown("**Hint 2**")
                    st.write(step["hint2"])
                    with st.expander("Hint 3 — Complete solution"):
                        st.caption("The complete solution includes comments so you can understand what each logical statement is doing.")
                        st.code(SOLUTIONS[filename], language="python" if filename.endswith(".py") else "text")
            with c3:
                if st.button("↺ Reset file", key=f"reset_{step_index}", use_container_width=True):
                    st.session_state.lab_files[filename] = STARTERS[filename]
                    st.session_state.lab_messages.pop(step_index, None)
                    st.rerun()

            if st.session_state.lab_messages.get(step_index) == "passed" and step_index < len(STEPS) - 1:
                if st.button("Next file →", key=f"next_{step_index}"):
                    st.session_state.lab_step += 1
                    st.rerun()

    st.divider()
    st.markdown("## 🧪 Run the project you built")

    all_done = all(st.session_state.lab_messages.get(i) == "passed" for i in range(len(STEPS)))
    if not all_done:
        st.warning("Validate all five project files first. The final test runner unlocks when your project structure is complete.")
        return

    st.success("Project structure complete. Now execute the controlled RAG + DeepEval regression harness.")
    st.code("pytest tests/test_deepeval.py -v", language="bash")

    run_col, download_col = st.columns(2)
    with run_col:
        if st.button("▶ Run DeepEval smoke test", type="primary", use_container_width=True):
            try:
                # Student Python is deliberately not exec()'d on the shared Streamlit server.
                # We validate their files above, then run the repository's controlled harness.
                from rag_eval import RAGPipeline
                from deepeval.metrics import AnswerRelevancyMetric, FaithfulnessMetric
                from deepeval.test_case import LLMTestCase

                key = st.secrets.get("OPENAI_API_KEY", os.getenv("OPENAI_API_KEY", ""))
                if not key:
                    st.error("OPENAI_API_KEY is not configured for this Streamlit app.")
                    return
                os.environ["OPENAI_API_KEY"] = key

                source_text = (
                    "Password reset links expire after 30 minutes.\n"
                    "Items may be returned within 30 days only if unopened.\n"
                    "New employees must complete their first 90 days in the office before remote work begins."
                )
                pipeline = RAGPipeline.from_text(source_text, top_k=3)
                question = "How long is a password reset link valid?"
                expected = "Password reset links expire after 30 minutes."
                result = pipeline.ask(question)
                case = LLMTestCase(
                    input=question,
                    actual_output=result.answer,
                    expected_output=expected,
                    retrieval_context=result.retrieval_context,
                )
                metrics = [AnswerRelevancyMetric(threshold=0.70), FaithfulnessMetric(threshold=0.80)]
                rows = []
                for metric in metrics:
                    metric.measure(case)
                    rows.append({
                        "Metric": metric.__class__.__name__,
                        "Score": round(float(metric.score), 3),
                        "Threshold": metric.threshold,
                        "Result": "PASS" if metric.is_successful() else "FAIL",
                        "Reason": metric.reason,
                    })
                st.write("**Runtime answer**")
                st.code(result.answer)
                st.write("**Retrieved context**")
                for chunk in result.retrieval_context:
                    st.write("•", chunk)
                st.dataframe(rows, use_container_width=True, hide_index=True)
            except Exception as exc:
                st.error(f"Smoke test could not complete: {exc}")

    with download_col:
        project = dict(st.session_state.lab_files)
        st.download_button(
            "↓ Download my finished project",
            data=_project_zip(project),
            file_name="my_deepeval_rag_project.zip",
            mime="application/zip",
            use_container_width=True,
        )

    st.markdown("### What the student has actually built")
    st.markdown(
        "**RAG pipeline → golden dataset → DeepEval pytest suite → thresholds → GitHub Actions quality gate.** "
        "The downloaded ZIP can be opened in VS Code and run locally with the same project structure used in the lesson."
    )
